---
fixtures:
  repositories:
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    systemd: 'https://github.com/camptocamp/puppet-systemd'