kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: check black
    image: python:3.7
    commands:
      - pip install black
      - black --check gmondflux.spec
      - black --check *.py
      - black --check gmondflux
      - black --check utils

  - name: pytest
    image: python:3.7
    commands:
      - pip install -r requirements.txt
      - pip install pytest
      - pytest ./gmondflux

  - name: docker build and deploy
    image: plugins/docker
    environment:
      SSH_KEY:
        from_secret: ssh-key
      PLUGIN_MIRROR:
        http://192.168.122.121:5000/
      PLUGIN_REPO:
        nerdworks/gmond2influx
      PLUGIN_DRY_RUN:
        true
      PLUGIN_TARGET:
        upload
      PLUGIN_BUILD_ARGS_FROM_ENV:
        SSH_KEY

  - name: prowl
    image: alpine:3.8
    commands:
      - apk add curl
      - chmod +x ./utils/prowl.sh
      - ./utils/prowl.sh build finished successfully
    environment:
      PROWL_APIKEY:
        from_secret: prowl-apikey
