export PATH=/opt/puppetlabs/bin:$PATH

alias cd..='cd ..'
alias ga='git add'
alias ga.='git add .'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gp='git pull'
alias gpp='git push'
alias grep='grep --color'
alias gs='git status'
alias l='ls -alh'
alias la='ls -alh'
alias ll='ls -l'
alias ls='ls --color=tty'

