FROM debian:stretch
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y wget
RUN wget https://apt.puppetlabs.com/puppet6-release-stretch.deb
RUN dpkg -i puppet*.deb

RUN apt-get update && apt-get install -y puppet-agent

WORKDIR /etc/puppetlabs/code/modules
ADD bashrc /root/.bashrc

RUN apt-get update && apt-get install -y systemd

